apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: container-handson-deployment
spec:
  scaleTargetRef:
    kind: Deployment
    apiVersion: apps/v1
    name: container-handson-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 40
