# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

steps:
# コンテナイメージのビルド
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/web-db:$SHORT_SHA', 'cloud-run-basic/web-db']
# コンテナイメージをContainer Registryへpush
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/web-db:$SHORT_SHA']
# Cloud Runのデプロイ
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'web-db', '--image', 'gcr.io/$PROJECT_ID/web-db:$SHORT_SHA', '--region', 'asia-northeast1', '--platform', 'managed', '--allow-unauthenticated']
# Cloud RunのLATESTヘルーティング
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'services', 'update-traffic', '--to-latest', 'web-db', '--region', 'asia-northeast1', '--platform', 'managed']
images:
- gcr.io/$PROJECT_ID/web-db:$SHORT_SHA